apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeewebappdemo-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: employeewebappdemo
  template:
    metadata:
      labels:
        app: employeewebappdemo
    spec:
      containers:
        - name: employeewebappdemo-container
          image: profilewebapp.azurecr.io/profilewebappdemo:6
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: employeewebappdemo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: employeewebappdemo
